<ADSWorkspace Revision="114" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="netlist.log" />
        <Log Name="search_history.log" />
        <Preferences Name="20230518_lib_lay.prf" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="_20230518.ds" />
        <Dataset Name="_20230518_1.ds" />
        <Dataset Name="HB1Tone_LoadPull.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_%H%B1%Tone_%Load%Pull_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_%H%B1%Tone_%Load%Pull_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230518#2d1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230518#2d1_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230518_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230518_schematic\annotation_map.xml" />
        <Data_Files Name="HB1Tone_LoadPull.ds" />
        <Data_Files Name="HB1Tone_LoadPull_data\logFile.txt" />
        <Data_Files Name="_20230518.ds" />
        <Data_Files Name="_20230518_1.ds" />
        <Data_Files Name="_20230518_1_data\logFile.txt" />
        <Data_Files Name="_20230518_data\logFile.txt" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_quantum" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <Library Name="20230518_lib" />
        <Cell Name="20230518_lib:fet_81xp" />
        <Cell Name="20230518_lib:tr_sample_forhyu" />
        <Dataset Name="_20230525.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525_%D%C_%I%V\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525_%D%C_%I%V\annotation_map.xml" />
        <Data_Files Name="_20230525.ds" />
        <Data_Files Name="_20230525_data\logFile.txt" />
        <ConfigFile Name="linecalc.cfg" />
        <Preferences Name="20230518_lib_sch.prf" />
        <Dataset Name="_20230525_1.ds" />
        <Dataset Name="_20230525_2.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525#2d2_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525#2d2_schematic\annotation_map.xml" />
        <Data_Files Name="_20230525_1.ds" />
        <Data_Files Name="_20230525_1_data\logFile.txt" />
        <Data_Files Name="_20230525_2.ds" />
        <Data_Files Name="_20230525_2_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525#2d1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525#2d1_schematic\annotation_map.xml" />
        <Folder Name="20230525">
            <Cell Name="20230518_lib:20230525" />
            <Cell Name="20230518_lib:20230525-1" />
            <Data_Display Name="20230525-1.dds" />
            <Cell Name="20230518_lib:20230525-2" />
            <Data_Display Name="20230525-2.dds" />
            <Data_Display Name="DC_IV.dds" />
        </Folder>
        <Dataset Name="_20230525_v1.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525_v1_%D%C_%I%V\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_20230525_v1_%D%C_%I%V\annotation_map.xml" />
        <Data_Files Name="_20230525_v1.ds" />
        <Data_Files Name="_20230525_v1_data\logFile.txt" />
        <Dataset Name="case1_matching.ds" />
        <Data_Files Name="case1_matching.ds" />
        <Data_Files Name="case1_matching_data\logFile.txt" />
        <Dataset Name="case1_power.ds" />
        <Data_Files Name="case1_power.ds" />
        <Data_Files Name="case1_power_data\logFile.txt" />
        <Dataset Name="case2_matching.ds" />
        <Data_Files Name="case2_matching.ds" />
        <Data_Files Name="case2_matching_data\logFile.txt" />
        <Dataset Name="case2_power.ds" />
        <Data_Files Name="case2_power.ds" />
        <Data_Files Name="case2_power_data\logFile.txt" />
        <Dataset Name="case3_matching.ds" />
        <Data_Files Name="case3_matching.ds" />
        <Data_Files Name="case3_matching_data\logFile.txt" />
        <Dataset Name="case3_power.ds" />
        <Data_Files Name="case3_power.ds" />
        <Data_Files Name="case3_power_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case3_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case3_matching_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case3_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case3_power_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case2_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case2_matching_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case2_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case2_power_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_matching_schematic\annotation_map.xml" />
        <Dataset Name="case4_matching.ds" />
        <Data_Files Name="case4_matching.ds" />
        <Data_Files Name="case4_matching_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case4_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case4_matching_schematic\annotation_map.xml" />
        <Dataset Name="case4_power.ds" />
        <Data_Files Name="case4_power.ds" />
        <Data_Files Name="case4_power_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case4_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case4_power_schematic\annotation_map.xml" />
        <Dataset Name="caseB_matching.ds" />
        <Data_Files Name="caseB_matching.ds" />
        <Data_Files Name="caseB_matching_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case%B_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case%B_matching_schematic\annotation_map.xml" />
        <Dataset Name="caseB_power.ds" />
        <Data_Files Name="caseB_power.ds" />
        <Data_Files Name="caseB_power_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case%B_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case%B_power_schematic\annotation_map.xml" />
        <Dataset Name="case1.ds" />
        <Data_Files Name="case1.ds" />
        <Data_Files Name="case1_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_schematic\annotation_map.xml" />
        <Dataset Name="case5_matching.ds" />
        <Data_Files Name="case5_matching.ds" />
        <Data_Files Name="case5_matching_data\logFile.txt" />
        <Dataset Name="DC_IV.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V_schematic\annotation_map.xml" />
        <Data_Files Name="DC_IV.ds" />
        <Data_Files Name="DC_IV_data\logFile.txt" />
        <Dataset Name="case1_DC_IV.ds" />
        <Data_Files Name="case1_DC_IV.ds" />
        <Data_Files Name="case1_DC_IV_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_%D%C_%I%V_%D%C_%I%V\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_%D%C_%I%V_%D%C_%I%V\annotation_map.xml" />
        <Dataset Name="case5_power.ds" />
        <Data_Files Name="case5_power.ds" />
        <Data_Files Name="case5_power_data\logFile.txt" />
        <Dataset Name="case6_matching.ds" />
        <Data_Files Name="case6_matching.ds" />
        <Data_Files Name="case6_matching_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case5_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case5_matching_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case5_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case5_power_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case6_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case6_matching_schematic\annotation_map.xml" />
        <Dataset Name="case6_power.ds" />
        <Data_Files Name="case6_power.ds" />
        <Data_Files Name="case6_power_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case6_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case6_power_schematic\annotation_map.xml" />
        <Folder Name="10 10 10">
            <Folder Name="case1(-1.40, 0.2)">
                <Cell Name="20230518_lib:case1_matching" />
                <Cell Name="20230518_lib:case1_power" />
                <Data_Display Name="case1_matching.dds" />
                <Data_Display Name="case1_power.dds" />
            </Folder>
            <Folder Name="case2(-1.1,0.3)">
                <Cell Name="20230518_lib:case2_matching" />
                <Data_Display Name="case2_matching.dds" />
                <Cell Name="20230518_lib:case2_power" />
                <Data_Display Name="case2_power.dds" />
            </Folder>
            <Folder Name="case3(-1.7, 0.1)">
                <Cell Name="20230518_lib:case3_matching" />
                <Cell Name="20230518_lib:case3_power" />
                <Data_Display Name="case3_matching.dds" />
                <Data_Display Name="case3_power.dds" />
            </Folder>
            <Folder Name="case4(-1.55,0.15)">
                <Cell Name="20230518_lib:case4_matching" />
                <Cell Name="20230518_lib:case4_power" />
                <Data_Display Name="case4_matching.dds" />
                <Data_Display Name="case4_power.dds" />
            </Folder>
            <Folder Name="caseB(-2,0)">
                <Cell Name="20230518_lib:caseB_matching" />
                <Cell Name="20230518_lib:caseB_power" />
                <Data_Display Name="caseB_matching.dds" />
                <Data_Display Name="caseB_power.dds" />
            </Folder>
            <Folder Name="DC_IV">
                <Data_Display Name="DC_IV_3Tr(10,10,10).dds" />
                <Cell Name="20230518_lib:case1_DC_IV" />
            </Folder>
        </Folder>
        <Folder Name="10 10 1*10">
            <Folder Name="case5(-1.55,0.15)">
                <Cell Name="20230518_lib:case5_matching" />
                <Data_Display Name="case5_matching.dds" />
                <Cell Name="20230518_lib:case5_power" />
                <Data_Display Name="DC_IV2.dds" />
                <Folder Name="DC_IV">
                    <Cell Name="20230518_lib:DC_IV" />
                </Folder>
                <Data_Display Name="case5_power.dds" />
            </Folder>
            <Folder Name="case6(-1.55,0.15)">
                <Cell Name="20230518_lib:case6_matching" />
                <Cell Name="20230518_lib:case6_power" />
                <Data_Display Name="case6_power.dds" />
                <Data_Display Name="case6_matching.dds" />
            </Folder>
        </Folder>
        <Data_Display Name="HB1Tone_LoadPull.dds" />
        <Cell Name="20230518_lib:HB1Tone_LoadPull" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case1_power_schematic\annotation_map.xml" />
        <Folder Name="10 10 5">
            <Cell Name="20230518_lib:DC_IV 10 10 5" />
            <Data_Display Name="DC_IV 10 10 5.dds" />
            <Cell Name="20230518_lib:case_matching" />
            <Cell Name="20230518_lib:case_power" />
            <Data_Display Name="case_matching.dds" />
            <Data_Display Name="case_power.dds" />
        </Folder>
        <Dataset Name="DC_IV_10_10_5.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2010#2010#205_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2010#2010#205_schematic\annotation_map.xml" />
        <Data_Files Name="DC_IV_10_10_5.ds" />
        <Data_Files Name="DC_IV_10_10_5_data\logFile.txt" />
        <Dataset Name="case_matching.ds" />
        <Data_Files Name="case_matching.ds" />
        <Data_Files Name="case_matching_data\logFile.txt" />
        <Dataset Name="case_power.ds" />
        <Data_Files Name="case_power.ds" />
        <Data_Files Name="case_power_data\logFile.txt" />
        <Folder Name="10 10 8">
            <Cell Name="20230518_lib:case_matching 10 10 8" />
            <Cell Name="20230518_lib:case_power 10 10 8" />
            <Cell Name="20230518_lib:DC_IV 10 10 8" />
            <Data_Display Name="DC_IV 10 10 8.dds" />
            <Data_Display Name="case_matching 10 10 8.dds" />
            <Data_Display Name="case_power 10 10 8.dds" />
        </Folder>
        <Dataset Name="DC_IV_10_10_8.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2010#2010#208_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2010#2010#208_schematic\annotation_map.xml" />
        <Data_Files Name="DC_IV_10_10_8.ds" />
        <Data_Files Name="DC_IV_10_10_8_data\logFile.txt" />
        <Dataset Name="case_matching_10_10_8.ds" />
        <Data_Files Name="case_matching_10_10_8.ds" />
        <Data_Files Name="case_matching_10_10_8_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case_matching#2010#2010#208_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_matching#2010#2010#208_schematic\annotation_map.xml" />
        <Dataset Name="case_power_10_10_8.ds" />
        <Data_Files Name="case_power_10_10_8.ds" />
        <Data_Files Name="case_power_10_10_8_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case_power#2010#2010#208_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_power#2010#2010#208_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_matching_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case_power_schematic\annotation_map.xml" />
        <Folder Name="10 10 10 1 1 1 ">
            <Cell Name="20230518_lib:DC_IV 33" />
            <Data_Display Name="DC_IV 33.dds" />
            <Cell Name="20230518_lib:case 33_matching" />
            <Cell Name="20230518_lib:case 33_power" />
        </Folder>
        <Dataset Name="DC_IV_33.ds" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2033_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_%D%C_%I%V#2033_schematic\annotation_map.xml" />
        <Data_Files Name="DC_IV_33.ds" />
        <Data_Files Name="DC_IV_33_data\logFile.txt" />
        <Dataset Name="case_33_matching.ds" />
        <Data_Files Name="case_33_matching.ds" />
        <Data_Files Name="case_33_matching_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case#2033_matching_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case#2033_matching_schematic\annotation_map.xml" />
        <Data_Display Name="case 33_matching.dds" />
        <Dataset Name="case_33_power.ds" />
        <Data_Files Name="case_33_power.ds" />
        <Data_Files Name="case_33_power_data\logFile.txt" />
        <Data_Files Name="dc_annotation\20230518_lib_case#2033_power_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\20230518_lib_case#2033_power_schematic\annotation_map.xml" />
    </Workspace>
</ADSWorkspace>
