<ADSWorkspace Revision="8" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_sources" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_rflib" />
        <Library Name="ads_simulation" />
        <Library Name="ads_datacmps" />
        <Library Name="1xEV" />
        <Library Name="3GPPFDD" />
        <Library Name="3GPPFDD_10_99" />
        <Library Name="Antennas_and_Propagation" />
        <Library Name="CDMA" />
        <Library Name="cdma2000" />
        <Library Name="Circuit_Cosimulation" />
        <Library Name="CMMB" />
        <Library Name="Controllers" />
        <Library Name="DTMB" />
        <Library Name="DTV" />
        <Library Name="EDGE" />
        <Library Name="GSM" />
        <Library Name="HDL_Blocks" />
        <Library Name="HSDPA" />
        <Library Name="HSUPA" />
        <Library Name="Instruments" />
        <Library Name="Interactive_Controls_and_Displays" />
        <Library Name="LTE" />
        <Library Name="Numeric" />
        <Library Name="Obsolete" />
        <Library Name="Signal_Converters" />
        <Library Name="Simulation_Sequencing" />
        <Library Name="Sinks" />
        <Library Name="SystemVue_Cosimulation" />
        <Library Name="TDSCDMA" />
        <Library Name="Timed" />
        <Library Name="UMB" />
        <Library Name="UWB" />
        <Library Name="WLAN" />
        <Library Name="WLAN_11n" />
        <Library Name="WMAN" />
        <Library Name="WMAN_16e" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="class PA_lib" />
        <Log Name="netlist.log" />
        <Dataset Name="DC_IV.ds" />
        <Data_Files Name="DC_IV.ds" />
        <Data_Files Name="DC_IV_data\logFile.txt" />
        <Log Name="search_history.log" />
        <ConfigFile Name="dds.cfg" />
        <Data_Display Name="_d_c__i_v.dds" />
        <Data_Display Name="Class_PA_LP.dds" />
        <Data_Display Name="class_PA_muratamatch.dds" />
        <Data_Display Name="DC_BLock_Cap.dds" />
        <Data_Display Name="DC_IV.dds" />
        <Data_Display Name="harmonic_tank.dds" />
        <Data_Display Name="HB1Tone_LoadPull.dds" />
        <Preferences Name="ads_builtin_lay.prf" />
        <Preferences Name="class PA_lib_lay.prf" />
        <Preferences Name="class PA_lib_sch.prf" />
        <Dataset Name="_d_c__i_v.ds" />
        <Dataset Name="Class_PA_LP.ds" />
        <Dataset Name="class_PA_muratamatch.ds" />
        <Dataset Name="DC_BLock_Cap.ds" />
        <Dataset Name="harmonic_tank.ds" />
        <Dataset Name="HB1Tone_LoadPull.ds" />
        <Dataset Name="HB1Tone_LoadPull1.ds" />
        <Data_Files Name="Class_PA_LP.ds" />
        <Data_Files Name="Class_PA_LP_data\logFile.txt" />
        <Data_Files Name="class_PA_muratamatch.ds" />
        <Data_Files Name="class_PA_muratamatch_data\logFile.txt" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%Class_%P%A_%L%P_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%Class_%P%A_%L%P_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%H%B1%Tone_%Load%Pull1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%H%B1%Tone_%Load%Pull1_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%H%B1%Tone_%Load%Pull_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_%H%B1%Tone_%Load%Pull_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_class_%P%A_muratamatch_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib_class_%P%A_muratamatch_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib__d_c__i_v_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20%P%A_lib__d_c__i_v_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\class#20_P_A_lib__D_C__I_V_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\class#20_P_A_lib__D_C__I_V_schematic\annotation_map.xml" />
        <Data_Files Name="DC_BLock_Cap.ds" />
        <Data_Files Name="DC_BLock_Cap_data\logFile.txt" />
        <Data_Files Name="harmonic_tank.ds" />
        <Data_Files Name="harmonic_tank_data\logFile.txt" />
        <Data_Files Name="HB1Tone_LoadPull.ds" />
        <Data_Files Name="HB1Tone_LoadPull1.ds" />
        <Data_Files Name="HB1Tone_LoadPull1_data\logFile.txt" />
        <Data_Files Name="HB1Tone_LoadPull_data\logFile.txt" />
        <Data_Files Name="_d_c__i_v.ds" />
        <Data_Files Name="_d_c__i_v_data\logFile.txt" />
        <Library Name="muRataLibWeb_tech" />
        <Library Name="muRataLibWeb" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Substrate Name="class PA_lib:substrate1.subst" />
        <Cell Name="class PA_lib:Class_PA_LP" />
        <Cell Name="class PA_lib:DC_BLock_Cap" />
        <Cell Name="class PA_lib:HB1Tone_LoadPull" />
        <Cell Name="class PA_lib:HB1Tone_LoadPull1" />
        <Cell Name="class PA_lib:_d_c__i_v" />
        <Cell Name="class PA_lib:cell_1" />
        <Cell Name="class PA_lib:class_PA_muratamatch" />
        <Cell Name="class PA_lib:fet_81xp" />
        <Cell Name="class PA_lib:harmonic_tank" />
    </Workspace>
</ADSWorkspace>
